Cleanup

diff --git a/mppnccombine b/mppnccombine
--- a/mppnccombine
+++ b/mppnccombine
@@ -50,6 +50,7 @@ if $unlimited; then
     exit 1
   fi
   ncrcat -O "${files[@]}" "$filename"
+  [ $? -ne 0 ] && echo "Error: ncrcat failed." && exit 1
 # Combine with mppnccombine
 else
   if ! which ./mppnccombine.x &>/dev/null; then
@@ -57,6 +58,7 @@ else
     exit 1
   fi
   ./mppnccombine.x "$filename" "${files[@]}"
+  [ $? -ne 0 ] && echo "Error: mppnccombine.x failed." && exit 1
 fi
 # Remove old files
 if $remove; then
