Cleanup

diff --git a/ncdivide b/ncdivide
--- a/ncdivide
+++ b/ncdivide
@@ -5,20 +5,17 @@
 # attributes so that mppnccombine can combine them. Will also slice the
 # file as parallel background processes.
 ################################################################################
-# Defaults and checks
+# Get arguments
 fix=false
 dname=lat # can also split along time dimension?
 nsplit=8
 silent=false
-if ! which ncks &>/dev/null; then
-  echo "Error: ncks not found, mppncdivide requires the NetCDF Operators (NCO) tools."
-  exit 1
-fi
-# Parse args
+source header.sh
 while [ $# -ne 0 ]; do
   case $1 in
     -d=*) dname=${1#*=} ;;
     -n=*) nsplit=${1#*=} ;;
+    -p=*) pmax=${1#*=} ;;
     -f) fix=true ;; # fix record dimension?
     -s) silent=true ;;
     -*) echo "Error: Unknown flag ${1}." && exit 1 ;;
@@ -26,7 +23,9 @@ while [ $# -ne 0 ]; do
   esac
   shift
 done
+[ -z "$pmax" ] && pmax=$nsplit # same as number of files
 ! [[ "$filename" =~ .nc$ ]] && echo "Error: File does not end in '.nc' extension." && exit 1
+! which ncks &>/dev/null && echo "Error: ncks not found, ncdivide requires the NetCDF Operators (NCO) tools." && exit 1
 
 # Get dimension size by parsing ncks
 # Could also parse ncdump, but this script requires NCO already so why not
@@ -45,14 +44,16 @@ if [ $((ndim % nsplit)) -ne 0 ]; then
   exit 1
 fi
 
-# Split up the file, making sure to add attributes to that mppnccombine
-# can combine it again.
-# WARNING: The attributes must be long type, not short
+# Optionally fix record dimension
 if $fix; then
   ncdump -h $filename | grep 'UNLIMITED' | grep $dname &>/dev/null
   [ $? -eq 0 ] && unlimited=true || unlimited=false
   $unlimited && flag="--fix_rec_dmn $dname" # required for mppnccombine
 fi
+# Split up the file, making sure to add attributes to that mppnccombine
+# can combine it again.
+# WARNING: The attributes must be long type, not short
+i=1
 for ni in $(seq 1 $nsplit); do
   file="${filename%.nc}.$(printf "%04d" $((ni-1))).nc"
   d1=$(((ni - 1)*ndim/nsplit)) # e.g. nsplit=10, ndim=200, goes 0, 20, 40, 60
@@ -65,16 +66,12 @@ for ni in $(seq 1 $nsplit); do
   } &
   pids+=($!)
   files+=("$file")
-done
-# Verify and exit
-for pid in ${pids[@]}; do
-  wait $pid
-  if [ $? -ne 0 ]; then
-    echo "Error: At least one of the ncks processes failed."
-    rm "${files[@]}" &>/dev/null # cleanup
-    exit 1
+  if [ $i -eq $pmax ]; then
+    i=1; pwait ${pids[@]}
+    unset pids
+  else
+    let i+=1
   fi
 done
-if ! $silent; then
-  echo "${files[@]}"
-fi
+# Verify and exit
+$silent || echo "${files[@]}"
diff --git a/ncparallel b/ncparallel
--- a/ncparallel
+++ b/ncparallel
@@ -8,11 +8,13 @@ keep=false
 dname=lat # can also split along time dimension?
 nsplit=8
 silent=false
+source header.sh
 while [ $# -ne 0 ]; do
   case "$1" in
     -n=*) nsplit="${1#*=}" ;;
     -d=*) dname="${1#*=}" ;;
     -p=*) pmax="${1#*=}" ;;
+    -f) flags="-f" ;;
     -k) keep=true ;;
     -s) silent=true ;;
     -*) echo "Error: Unknown argument ${1}." && exit 1 ;;
@@ -21,11 +23,7 @@ while [ $# -ne 0 ]; do
   shift
 done
 [ -z "$pmax" ] && pmax=$nsplit # same as number of files
-# Checks
-if [ ${#args[@]} -ne 3 ]; then
-  echo "Error: Usage is ncparallel 'command' 'input.nc' 'output.nc', where command is any command that accepts an input file and saves data to an output file."
-  exit 1
-fi
+[ ${#args[@]} -ne 3 ] && echo "Error: Usage is ncparallel 'command' 'input.nc' 'output.nc', where command is any command that accepts an input file and saves data to an output file." && exit 1
 dir=${0%/*}
 cmd="${args[0]}"
 input="${args[1]}"
@@ -33,23 +31,12 @@ output="${args[2]}"
 
 # Divide into smaller files and collect names in a bash array
 # Format will be input.0000.nc, input.0001.nc, etc.
+# TODO: Divide up to n blocks
 t=$(date +%s)
 $silent || echo "Dividing file: ${input##*/}"
-inputs=($($dir/ncdivide -n=$nsplit -d=$dname "$input"))
+inputs=($($dir/ncdivide -p=$pmax -n=$nsplit -d=$dname $flags "$input"))
 [ $? -ne 0 ] && echo "Error: ncdivide failed." && exit 1
 $silent || echo "Elapsed time: $(($(date +%s) - t))s."
-
-# Function that waits for background processes to finish, and makes
-# sure they were all successful
-pwait() {
-  for pid in $@; do
-    wait $pid
-    if [ $? -ne 0 ]; then
-      echo "Error: One of the processes failed."
-      exit 1
-    fi
-  done
-}
 
 # Generate background processes for each file, for example a python script
 # that creates a new NetCDF file from some input NetCDF file.
